services:
  nginx-sample:
    image: nginx:1.23-alpine
    container_name: nginx-sample-docker
    restart: unless-stopped
    volumes:
      - ../src:/var/www/html
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ../data/nginx/log:/var/log/nginx
      - ../data/xdebug/log:/var/log/xdebug
    links:
      - php-sample
    ports:
      - "80:80"
  db-sample:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: db-sample-docker
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: M6Yp5Tho4mT3mT7upGSY
      MYSQL_DATABASE: sampledb
      MYSQL_USER: acquire5171
      MYSQL_PASSWORD: x9uiJujVNSUCxBZhSLiM
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 20
  php-sample:
    build:
      context: .
      dockerfile: ./phpfpm/Dockerfile
    image: php-sample-harmony
    container_name: php-sample-docker
    restart: unless-stopped
    depends_on:
      db-sample:
        condition: service_healthy
    volumes:
      - ../src:/var/www/html
      - ../../core/src:/var/www/html/core
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # The same name server like PHPSTORM
      PHP_IDE_CONFIG: serverName=localhost
      # https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: debug,coverage
      PHPUNIT_DB_HOST: db-sample
      PHPUNIT_DB_NAME: sampledb
      PHPUNIT_DB_USER: root
      PHPUNIT_DB_PASSWORD: M6Yp5Tho4mT3mT7upGSY
networks:
  default:
    name: sample-network
