# Base stack
version: '3.7'

services:
  mysql-sample:
    image: mysql:8
    container_name: mysql-sample-docker
    restart: unless-stopped
    volumes:
      - ../data/mysql/lib:/var/lib/mysql
      - ../data/mysql/log:/var/log/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'jgjsF2jwMUSP'
      MYSQL_DATABASE: 'sampledb'
      MYSQL_USER: 'sampleuser'
      MYSQL_PASSWORD: 'JhDdULdg4CgK'
  nginx-sample:
    image: nginx:1.14-alpine
    container_name: nginx-sample-docker
    restart: unless-stopped
    volumes:
      - ../src:/var/www/html
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ../data/nginx/log:/var/log/nginx
      - ../data/xdebug/log:/var/log/xdebug
    links:
      - php-sample
    ports:
      - '80:80'
  php-sample:
    build:
      context: .
      dockerfile: ./phpfpm/Dockerfile
    image: php-sample-harmony
    container_name: php-sample-docker
    restart: unless-stopped
    volumes:
      - ../src:/var/www/html
      - ../../core/src:/var/www/html/core
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # The same name server like PHPSTORM
      - PHP_IDE_CONFIG=serverName=localhost
      # https://xdebug.org/docs/all_settings#mode
      - XDEBUG_MODE=debug,coverage
networks:
  default:
    name: sample-network
