# Base stack
version: "3.9"

services:
  nginx-sample:
    image: nginx:1.23-alpine
    container_name: nginx-sample-docker
    restart: unless-stopped
    volumes:
      - ../src:/var/www/html
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ../data/nginx/log:/var/log/nginx
      - ../data/xdebug/log:/var/log/xdebug
    links:
      - php-sample
    ports:
      - "80:80"
  php-sample:
    build:
      context: .
      dockerfile: ./phpfpm/Dockerfile
    image: php-sample-harmony
    container_name: php-sample-docker
    restart: unless-stopped
    volumes:
      - ../src:/var/www/html
      - ../../core/src:/var/www/html/core
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # The same name server like PHPSTORM
      - PHP_IDE_CONFIG=serverName=localhost
      # https://xdebug.org/docs/all_settings#mode
      - XDEBUG_MODE=debug,coverage
networks:
  default:
    name: sample-network
