name: Static Analysis
# Trigger this job on:
on:
    push:
    pull_request:
        branches:
            - master

jobs:
    build:
        # Job name
        name: Static Analysis
        runs-on: ubuntu-latest
#        defaults:
#            run:
#                shell: bash
#                working-directory: ./sample/src
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.3'
                    tools: php-cs-fixer, phpcs, phpmd, phpstan, psalm

            -   name: Validate composer
                run: composer validate
                working-directory: ./sample/src

            -   name: Composer Install
                run: composer install --prefer-dist --no-progress --no-suggest
                working-directory: ./sample/src

            -   name: Psalm
#                run: psalm --show-info=true
                run: ./vendor/bin/psalm --show-info=true
                working-directory: ./sample/src

            -   name: PHPStan
                run: phpstan analyse -l max ./sample/src/app ./core/src ./eloquent/src
#                run: ./vendor/bin/phpstan analyse -l max app ../../core ../../eloquent

            -   name: PHP Mess Detector
                run: phpmd ./sample/src/app,./core/src,./eloquent/src text codesize,design,unusedcode

            -   name: PHP_CodeSniffer
                run: phpcs --standard=PSR2 ./sample/src/app ./core/src ./eloquent/src

            -   name: PHP Coding Standards Fixer
                run: |
                    php-cs-fixer fix --dry-run --diff ./sample/src/app
                    php-cs-fixer fix --dry-run --diff ./core/src
                    php-cs-fixer fix --dry-run --diff ./eloquent/src
