name: Static Analysis
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phpmd
      - name: Link Harmony PHP
        run: ln -s ./core/src ./sample/src/core && ln -s ./eloquent/src ./sample/src/eloquent
        working-directory: .
      - name: Validate composer
        run: composer validate
        working-directory: ./sample/src
      - name: Composer Install
        run: composer install --prefer-dist --no-progress
        working-directory: ./sample/src
      - name: PHPStan
        run: ./vendor/bin/phpstan analyse -l max app ../../core ../../eloquent
        working-directory: ./sample/src
      - name: PHP Mess Detector
        run: phpmd ./sample/src/app,./core/src,./eloquent/src text codesize,design,cleancode
      - name: Psalm
        run: ./vendor/bin/psalm --show-info=true --php-version=8.0
        working-directory: ./sample/src
