name: Harmony PHP | Static Analysis
# Trigger this job on:
on: [push]

jobs:
    build:
        # Job name
        name: Static Analysis
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./sample
        steps:
            -   uses: actions/checkout@v2

            -   name: Time
                run: date

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: Run Psalm
                run: ./vendor/bin/psalm --show-info=true

