name: Harmony PHP | Static Analysis
# Trigger this job on:
on:
    push:
    pull_request:
        branches:
            - master

jobs:
    build:
        # Job name
        name: Static Analysis
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./sample/src
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.3'

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: Run Psalm
                run: ./vendor/bin/psalm --show-info=true

            -   name: Run PHPStan
                run: ./vendor/bin/phpstan analyse -l max app ../../core ../../eloquent
